#!/usr/bin/env node
/**
 * Reset ACO Catalog Data
 *
 * Deletes products, prices, and price books from ACO by reading local JSON files.
 * Follows the pattern from adobe-commerce/aco-sample-catalog-data-ingestion.
 *
 * ⚠️ IMPORTANT LIMITATION:
 * This script only deletes data that matches SKUs in local JSON files (./data/buildright/).
 * It does NOT query ACO to find all existing data because:
 * - ACO SDK does not provide a "list all products" method
 * - GraphQL queries require complex schema knowledge and search index setup
 *
 * If you have existing data in ACO that was NOT generated by these scripts:
 * - Option 1: Export your ACO data to local JSON files first, then run this script
 * - Option 2: Use Adobe Commerce Admin UI to delete data manually
 * - Option 3: Write custom deletion scripts using ACO GraphQL with correct schema
 *
 * @module scripts/reset-catalog
 *
 * @example
 * # Dry-run (show what would be deleted from local files)
 * node scripts/reset-catalog.js --dry-run
 *
 * # Reset with confirmation prompt
 * node scripts/reset-catalog.js
 *
 * # Force reset without confirmation
 * node scripts/reset-catalog.js --force
 */

import { promises as fs } from 'fs';
import * as readline from 'readline/promises';
import { stdin as input, stdout as output } from 'process';
import { getACOClient } from '../utils/aco-client.js';
import logger from '../utils/logger.js';
import { validateIngestConfig } from './config/ingest-config.js';

const BATCH_SIZE = 100;
const DATA_DIR = './data/buildright';

/**
 * Prompt user for confirmation
 *
 * @param {string} message - Confirmation message
 * @returns {Promise<boolean>} True if user confirmed
 */
async function promptConfirmation(message) {
  const rl = readline.createInterface({ input, output });

  try {
    const answer = await rl.question(`${message} (yes/no): `);
    return answer.toLowerCase() === 'yes';
  } finally {
    rl.close();
  }
}

/**
 * Get batch number for logging
 *
 * @param {number} index - Item index
 * @returns {number} Batch number
 */
function getBatchNumber(index) {
  return Math.floor(index / BATCH_SIZE) + 1;
}

/**
 * Load JSON file safely
 *
 * @param {string} filepath - Path to JSON file
 * @returns {Promise<Array>} Parsed JSON array or empty array if file doesn't exist
 */
async function loadJSON(filepath) {
  try {
    const data = await fs.readFile(filepath, 'utf-8');
    return JSON.parse(data);
  } catch (error) {
    if (error.code === 'ENOENT') {
      logger.warn(`File not found: ${filepath}`);
      return [];
    }
    throw error;
  }
}

/**
 * Delete prices from ACO
 *
 * @param {Object} client - ACO SDK client
 * @param {boolean} dryRun - Dry-run mode
 * @returns {Promise<Object>} Deletion results
 */
async function deletePrices(client, dryRun = false) {
  logger.info('Loading prices from file...');
  const prices = await loadJSON(`${DATA_DIR}/prices.json`);

  if (prices.length === 0) {
    logger.info('No prices found to delete');
    return { deleted: 0, total: 0 };
  }

  logger.info(`Found ${prices.length} prices to delete`);

  if (dryRun) {
    logger.info('[DRY-RUN] Would delete prices in batches of', BATCH_SIZE);
    return { deleted: 0, total: prices.length, dryRun: true };
  }

  let deletedCount = 0;
  const pricesToDelete = prices.map(price => ({
    sku: price.sku,
    priceBookId: price.priceBookId
  }));

  // Process in batches
  for (let i = 0; i < pricesToDelete.length; i += BATCH_SIZE) {
    const batch = pricesToDelete.slice(i, i + BATCH_SIZE);
    const batchNum = getBatchNumber(i);

    try {
      const response = await client.deletePrices(batch);
      deletedCount += response.data?.accepted || 0;
      logger.info(`Batch ${batchNum}: Deleted ${response.data?.accepted || 0} prices`);
    } catch (error) {
      logger.error(`Batch ${batchNum} failed:`, error.message);
    }
  }

  logger.info(`Price deletion complete: ${deletedCount}/${prices.length} deleted`);
  return { deleted: deletedCount, total: prices.length };
}

/**
 * Delete price books from ACO
 *
 * @param {Object} client - ACO SDK client
 * @param {boolean} dryRun - Dry-run mode
 * @returns {Promise<Object>} Deletion results
 */
async function deletePriceBooks(client, dryRun = false) {
  logger.info('Loading price books from file...');
  const priceBooks = await loadJSON(`${DATA_DIR}/price-books.json`);

  if (priceBooks.length === 0) {
    logger.info('No price books found to delete');
    return { deleted: 0, total: 0 };
  }

  logger.info(`Found ${priceBooks.length} price books to delete`);

  if (dryRun) {
    logger.info('[DRY-RUN] Would delete price books in batches of', BATCH_SIZE);
    return { deleted: 0, total: priceBooks.length, dryRun: true };
  }

  let deletedCount = 0;
  const priceBookIds = priceBooks.map(pb => ({
    priceBookId: pb.priceBookId
  }));

  // Process in batches
  for (let i = 0; i < priceBookIds.length; i += BATCH_SIZE) {
    const batch = priceBookIds.slice(i, i + BATCH_SIZE);
    const batchNum = getBatchNumber(i);

    try {
      const response = await client.deletePriceBooks(batch);
      deletedCount += response.data?.accepted || 0;
      logger.info(`Batch ${batchNum}: Deleted ${response.data?.accepted || 0} price books`);
    } catch (error) {
      logger.error(`Batch ${batchNum} failed:`, error.message);
    }
  }

  logger.info(`Price book deletion complete: ${deletedCount}/${priceBooks.length} deleted`);
  return { deleted: deletedCount, total: priceBooks.length };
}

/**
 * Delete products from ACO
 *
 * @param {Object} client - ACO SDK client
 * @param {boolean} dryRun - Dry-run mode
 * @returns {Promise<Object>} Deletion results
 */
async function deleteProducts(client, dryRun = false) {
  logger.info('Loading products from files...');

  // Load all product types
  const products = await loadJSON(`${DATA_DIR}/products.json`);
  const variants = await loadJSON(`${DATA_DIR}/variants.json`);
  const bundles = await loadJSON(`${DATA_DIR}/bundles.json`);

  const allProducts = [...products, ...variants, ...bundles];

  if (allProducts.length === 0) {
    logger.info('No products found to delete');
    return { deleted: 0, total: 0 };
  }

  logger.info(`Found ${allProducts.length} products to delete (${products.length} standard, ${variants.length} variants, ${bundles.length} bundles)`);

  if (dryRun) {
    logger.info('[DRY-RUN] Would delete products in batches of', BATCH_SIZE);
    return { deleted: 0, total: allProducts.length, dryRun: true };
  }

  let deletedCount = 0;
  const productsToDelete = allProducts.map(product => ({
    sku: product.sku,
    source: product.source || { locale: 'en-US' }
  }));

  // Process in batches
  for (let i = 0; i < productsToDelete.length; i += BATCH_SIZE) {
    const batch = productsToDelete.slice(i, i + BATCH_SIZE);
    const batchNum = getBatchNumber(i);

    try {
      const response = await client.deleteProducts(batch);
      deletedCount += response.data?.accepted || 0;
      logger.info(`Batch ${batchNum}: Deleted ${response.data?.accepted || 0} products`);
    } catch (error) {
      logger.error(`Batch ${batchNum} failed:`, error.message);
    }
  }

  logger.info(`Product deletion complete: ${deletedCount}/${allProducts.length} deleted`);
  return { deleted: deletedCount, total: allProducts.length };
}

/**
 * Delete metadata from ACO
 *
 * @param {Object} client - ACO SDK client
 * @param {boolean} dryRun - Dry-run mode
 * @returns {Promise<Object>} Deletion results
 */
async function deleteMetadata(client, dryRun = false) {
  logger.info('Loading metadata from file...');
  const metadata = await loadJSON(`${DATA_DIR}/metadata.json`);

  if (metadata.length === 0) {
    logger.info('No metadata found to delete');
    return { deleted: 0, total: 0 };
  }

  logger.info(`Found ${metadata.length} metadata items to delete`);

  if (dryRun) {
    logger.info('[DRY-RUN] Would delete metadata in batches of', BATCH_SIZE);
    return { deleted: 0, total: metadata.length, dryRun: true };
  }

  let deletedCount = 0;
  const metadataToDelete = metadata.map(meta => ({
    code: meta.attributeId,
    source: { locale: 'en-US' }
  }));

  // Process in batches
  for (let i = 0; i < metadataToDelete.length; i += BATCH_SIZE) {
    const batch = metadataToDelete.slice(i, i + BATCH_SIZE);
    const batchNum = getBatchNumber(i);

    try {
      const response = await client.deleteProductMetadata(batch);
      deletedCount += response.data?.accepted || 0;
      logger.info(`Batch ${batchNum}: Deleted ${response.data?.accepted || 0} metadata items`);
    } catch (error) {
      logger.error(`Batch ${batchNum} failed:`, error.message);
    }
  }

  logger.info(`Metadata deletion complete: ${deletedCount}/${metadata.length} deleted`);
  return { deleted: deletedCount, total: metadata.length };
}

/**
 * Reset catalog data
 *
 * @param {Object} options - Reset options
 * @returns {Promise<Object>} Reset results
 */
export async function resetCatalog(options = {}) {
  const {
    dryRun = false,
    force = false
  } = options;

  logger.info('Catalog Reset Started', { dryRun, force, dataDir: DATA_DIR });

  // Load files to count items
  const products = await loadJSON(`${DATA_DIR}/products.json`);
  const variants = await loadJSON(`${DATA_DIR}/variants.json`);
  const bundles = await loadJSON(`${DATA_DIR}/bundles.json`);
  const prices = await loadJSON(`${DATA_DIR}/prices.json`);
  const priceBooks = await loadJSON(`${DATA_DIR}/price-books.json`);
  const metadata = await loadJSON(`${DATA_DIR}/metadata.json`);

  const totalProducts = products.length + variants.length + bundles.length;
  const stats = {
    products: totalProducts,
    prices: prices.length,
    priceBooks: priceBooks.length,
    metadata: metadata.length
  };

  logger.info('Data found in local files:', stats);

  if (totalProducts === 0 && prices.length === 0 && priceBooks.length === 0 && metadata.length === 0) {
    logger.warn('No data found to delete. Run generation scripts first.');
    return { cancelled: false, success: true, reason: 'no_data' };
  }

  // Confirm if not forced
  if (!dryRun && !force) {
    const confirmed = await promptConfirmation(
      `Delete all catalog data (${totalProducts} products, ${prices.length} prices, ${priceBooks.length} price books, ${metadata.length} metadata)? This cannot be undone!`
    );

    if (!confirmed) {
      logger.info('Reset cancelled by user');
      return { cancelled: true };
    }
  }

  const client = getACOClient();

  const results = {
    success: true,
    dryRun
  };

  // Delete in proper order (child data first, then parent data)
  // 1. Delete prices (reference products and price books)
  try {
    results.prices = await deletePrices(client, dryRun);
  } catch (error) {
    logger.error('Failed to delete prices:', error.message);
    results.success = false;
  }

  // 2. Delete price books
  try {
    results.priceBooks = await deletePriceBooks(client, dryRun);
  } catch (error) {
    logger.error('Failed to delete price books:', error.message);
    results.success = false;
  }

  // 3. Delete products (variants and bundles should be deleted with parents)
  try {
    results.products = await deleteProducts(client, dryRun);
  } catch (error) {
    logger.error('Failed to delete products:', error.message);
    results.success = false;
  }

  // 4. Delete metadata (should be last)
  try {
    results.metadata = await deleteMetadata(client, dryRun);
  } catch (error) {
    logger.error('Failed to delete metadata:', error.message);
    results.success = false;
  }

  logger.info('Catalog Reset Complete', results);

  // Report on what was actually deleted
  const totalDeleted = (results.prices?.deleted || 0) + (results.priceBooks?.deleted || 0) +
                       (results.products?.deleted || 0) + (results.metadata?.deleted || 0);
  const totalAttempted = (results.prices?.total || 0) + (results.priceBooks?.total || 0) +
                         (results.products?.total || 0) + (results.metadata?.total || 0);

  if (!dryRun && totalAttempted > 0 && totalDeleted === 0) {
    logger.warn('');
    logger.warn('⚠️  WARNING: 0 items deleted from ACO (attempted to delete ' + totalAttempted + ' items)');
    logger.warn('   Possible reasons:');
    logger.warn('   1. Data in local files was never ingested to ACO');
    logger.warn('   2. SKUs in local files don\'t match SKUs in ACO catalog');
    logger.warn('   3. Data was already deleted or expired');
    logger.warn('');
    logger.warn('   If you have data in ACO that needs deleting:');
    logger.warn('   - Ensure local JSON files match what was ingested');
    logger.warn('   - Or delete manually via Adobe Commerce Admin UI');
    logger.warn('');
  } else if (!dryRun && totalDeleted > 0) {
    logger.info('');
    logger.info(`✅ Successfully deleted ${totalDeleted} of ${totalAttempted} items from ACO`);
    if (totalDeleted < totalAttempted) {
      logger.warn(`   Note: ${totalAttempted - totalDeleted} items were not found in ACO`);
    }
    logger.info('');
  }

  return results;
}

// CLI execution
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const options = {
    dryRun: args.includes('--dry-run'),
    force: args.includes('--force')
  };

  try {
    // Validate configuration
    validateIngestConfig();

    // Run reset
    const results = await resetCatalog(options);

    if (results.cancelled) {
      logger.info('Reset cancelled');
      process.exit(0);
    }

    if (results.reason === 'no_data') {
      logger.info('No data to delete');
      process.exit(0);
    }

    if (!results.success) {
      logger.error('Reset completed with errors');
      process.exit(1);
    }

    logger.info('Reset successful');
    process.exit(0);

  } catch (error) {
    logger.error('Reset failed', {
      error: error.message,
      stack: error.stack
    });
    process.exit(1);
  }
}
